### ISSUE TITLE
Cleanup API specification

### ISSUE THREAD

**Issue by hannahcoe** [SaplingSquad/SoftwareEngineering-WS2025-SaplingSquad#49]
Refactor api-spec

- [x] association -> organization, assoc -> orga
- [x] additionalProperties with enum as component *1
- [x] informations -> description
- [x] ID in comments, ...Id in variables
- [x] .../byId -> .../{byId}
- [x] component where possible

*1
```
type: object
additionalProperties:
  type: string
  enum: [pos, neu, neg]
  description: ...
```
